server:
  port: 8888

spring:
  application:
    name: server-registry

eureka:
  client:
    service-url:
      defaultZone: http://106.13.83.153:8888/eureka,http://182.254.188.234:8888/eureka
    register-with-eureka: true
  server:
    enable-self-preservation: false

  instance:
    ip-address: 23.105.202.251
    prefer-ip-address: true
